# Cookson Solids
# A Cookson solid is a closed, symmetric, spherical polyhedron generated by projecting
# the vertices of a non-triangular Catalan solid onto a unit sphere, and subsequently
# subdividing any resulting non-planar faces along internal creases to restore strict
# three-dimensional planarity.

"""
    cookson(P::Polyhedron; radius::Real=1.0)

Constructs the Cookson solid corresponding to a polyhedron `P` by projecting its vertices
onto a sphere of the given `radius`, and subdividing any resulting non-planar faces along
internal creases to restore strict three-dimensional planarity.
"""
function cookson(P::Polyhedron; radius::Real=1.0)
    v_sph = Pt3{Float64}[radius * (v / norm(v)) for v in P.v]
    return convex_hull(v_sph; merge_coplanar=true)
end

# The 6 Canonical Cookson Solids

"""
    cooksonian_rhombic_dodecahedron(; radius::Real=1.0)

Constructs the Cooksonian Rhombic Dodecahedron (V=14, F=24).
Derived by projecting the 12 rhombic faces of the Rhombic Dodecahedron onto a sphere,
where the rhombi crease across a diagonal into 24 triangular faces.
"""
function cooksonian_rhombic_dodecahedron(; radius::Real=1.0)
    return cookson(rhombic_dodecahedron(); radius=radius)
end

"""
    cooksonian_rhombic_triacontahedron(; radius::Real=1.0)

Constructs the Cooksonian Rhombic Triacontahedron (V=32, F=60).
Derived by projecting the 30 rhombic faces of the Rhombic Triacontahedron onto a sphere,
where the rhombi crease across a diagonal into 60 triangular faces.
"""
function cooksonian_rhombic_triacontahedron(; radius::Real=1.0)
    return cookson(rhombic_triacontahedron(); radius=radius)
end

"""
    cooksonian_deltoidal_icositetrahedron(; radius::Real=1.0)

Constructs the Cooksonian Deltoidal Icositetrahedron (V=26, F=48).
Derived by projecting the 24 kite-shaped faces of the Deltoidal Icositetrahedron onto a sphere,
where the kites crease across their diagonals into 48 triangular faces.
"""
function cooksonian_deltoidal_icositetrahedron(; radius::Real=1.0)
    return cookson(deltoidal_icositetrahedron(); radius=radius)
end

"""
    cooksonian_deltoidal_hexecontahedron(; radius::Real=1.0)

Constructs the Cooksonian Deltoidal Hexecontahedron (V=62, F=120).
Derived by projecting the 60 kite-shaped faces of the Deltoidal Hexecontahedron onto a sphere,
where the kites crease across their diagonals into 120 triangular faces.
"""
function cooksonian_deltoidal_hexecontahedron(; radius::Real=1.0)
    return cookson(deltoidal_hexecontahedron(); radius=radius)
end

"""
    cooksonian_pentagonal_icositetrahedron(; radius::Real=1.0)

Constructs the Cooksonian Pentagonal Icositetrahedron (V=38, F=48).
Derived by projecting the 24 irregular pentagonal faces of the Pentagonal Icositetrahedron onto a sphere,
which crease into a uniform mosaic of 24 trapezoids and 24 triangles.
"""
function cooksonian_pentagonal_icositetrahedron(; radius::Real=1.0)
    return cookson(pentagonal_icositetrahedron(); radius=radius)
end

"""
    cooksonian_pentagonal_hexecontahedron(; radius::Real=1.0)

Constructs the canonical Cooksonian Pentagonal Hexecontahedron (V=92, F=120).
Derived by projecting the 60 irregular pentagonal faces of the Pentagonal Hexecontahedron onto a sphere.
The 60 pentagons fracture into exactly 120 planar faces: 60 trapezoids and 60 scalene triangles.
"""
function cooksonian_pentagonal_hexecontahedron(; radius::Real=1.0)
    return cookson(pentagonal_hexecontahedron(); radius=radius)
end

const COOKSON_SOLID_MAP = Dict{Symbol, Function}(
    :rhombic_dodecahedron => cooksonian_rhombic_dodecahedron,
    :cooksonian_rhombic_dodecahedron => cooksonian_rhombic_dodecahedron,
    :rhombic_triacontahedron => cooksonian_rhombic_triacontahedron,
    :cooksonian_rhombic_triacontahedron => cooksonian_rhombic_triacontahedron,
    :deltoidal_icositetrahedron => cooksonian_deltoidal_icositetrahedron,
    :cooksonian_deltoidal_icositetrahedron => cooksonian_deltoidal_icositetrahedron,
    :deltoidal_hexecontahedron => cooksonian_deltoidal_hexecontahedron,
    :cooksonian_deltoidal_hexecontahedron => cooksonian_deltoidal_hexecontahedron,
    :pentagonal_icositetrahedron => cooksonian_pentagonal_icositetrahedron,
    :cooksonian_pentagonal_icositetrahedron => cooksonian_pentagonal_icositetrahedron,
    :pentagonal_hexecontahedron => cooksonian_pentagonal_hexecontahedron,
    :cooksonian_pentagonal_hexecontahedron => cooksonian_pentagonal_hexecontahedron
)

const COOKSON_SOLID_ORDER = [
    :cooksonian_rhombic_dodecahedron,
    :cooksonian_rhombic_triacontahedron,
    :cooksonian_deltoidal_icositetrahedron,
    :cooksonian_deltoidal_hexecontahedron,
    :cooksonian_pentagonal_icositetrahedron,
    :cooksonian_pentagonal_hexecontahedron
]

"""
    cookson(name::Symbol; radius::Real=1.0)
    cookson(index::Integer; radius::Real=1.0)

Access any of the 6 canonical Cookson solids by name symbol or index (1-6).
"""
function cookson(name::Symbol; radius::Real=1.0)
    haskey(COOKSON_SOLID_MAP, name) || error("Unknown Cookson solid: $name. Available: $(keys(COOKSON_SOLID_MAP))")
    return COOKSON_SOLID_MAP[name](; radius=radius)
end

function cookson(index::Integer; radius::Real=1.0)
    1 <= index <= 6 || error("Cookson solid index must be between 1 and 6.")
    return cookson(COOKSON_SOLID_ORDER[index]; radius=radius)
end
